I'm sorry, but an uncaught exception occurred.

While running game code:
NameError: name 'Isabella' is not defined. Did you mean: 'isabelle'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "game/intro.rpy", line 1098, in script
    Isabella "(This idiot must be messing with me.)"
Exception: Sayer 'Isabella' is not defined.

-- Full Traceback ------------------------------------------------------------

Traceback (most recent call last):
  File "renpy/ast.py", line 625, in eval_who
    return renpy.python.py_eval(who)
           ~~~~~~~~~~~~~~~~~~~~^^^^^
  File "renpy/python.py", line 1292, in py_eval
    return py_eval_bytecode(code, globals, locals)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/python.py", line 1285, in py_eval_bytecode
    return eval(bytecode, globals, locals)
           ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<none>", line 1, in <module>
NameError: name 'Isabella' is not defined. Did you mean: 'isabelle'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "game/intro.rpy", line 1098, in script
    Isabella "(This idiot must be messing with me.)"
  File "renpy/ast.py", line 2915, in execute
    Say.execute(self)
    ~~~~~~~~~~~^^^^^^
  File "renpy/ast.py", line 956, in execute
    who = eval_who(self.who, self.who_fast)
          ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/ast.py", line 627, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'Isabella' is not defined.

macOS-15.6.1-arm64-arm-64bit arm64
Ren'Py 8.4.1.25072401
Axels Fantasy 1.0
Tue Oct 21 15:12:36 2025
